sudo: required

language: python

python:
  - "3.6"

services:
  - docker

before_install:
  - docker build -t jsonschema2db .
  # Make sure Sphinx works
  - pip install . sphinx
  - sphinx-build -M html docs/ docs/_build/ -W

script:
  - docker run jsonschema2db
