sudo: required

language: python

python:
  - "3.6"

services:
  - docker

before_install:
  - docker build -t jsonschema2db .
  # Make sure Sphinx works and we can build documentation
  - pip install sphinx
  - python setup.py build_sphinx

script:
  - docker run jsonschema2db
